import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { account, item, openEditor, picture } from './helpers'

test('连续录题保留分类、清空上一题内容并恢复下一题草稿', async ({ page }) => {
  const user = await account(page)
  const chapters = await (await page.request.get('/api/v1/chapters')).json()
  const chapter = chapters.find((value: { subject: string }) => value.subject === 'math')
  const editor = await openEditor(page, true)
  await editor.getByRole('button', { name: '数学', exact: true }).click()
  await editor.getByRole('combobox', { name: '章节', exact: true }).selectOption(chapter.id)
  await editor.getByLabel('标题').fill('连续录题的第一道')
  await editor.getByLabel('问题 / 题干附件', { exact: true }).setInputFiles(picture)
  await expect(editor.getByAltText('问题 / 题干图片 1')).toBeVisible()
  await editor.getByLabel('答案 / 解析', { exact: true }).fill('第一道题的答案')
  await editor.getByRole('button', { name: '复盘与标记' }).click()
  await editor.getByRole('button', { name: '较难', exact: true }).click()
  await editor.getByLabel('这次为什么出错？').fill('第一题的错因')
  await editor.getByLabel('标签').fill('第一题标签')
  await editor.getByRole('button', { name: '保存并录下一题' }).click()
  await expect(editor.getByLabel('标题')).toHaveValue('')
  await expect(editor.getByLabel('标题')).toBeFocused()
  await expect(editor.getByRole('combobox', { name: '章节', exact: true })).toHaveValue(chapter.id)
  await expect(editor.getByRole('combobox', { name: '内容类型', exact: true })).toHaveValue('problem')
  await expect(editor.getByAltText('问题 / 题干图片 1')).toHaveCount(0)
  await expect(editor.getByLabel('答案 / 解析', { exact: true })).toHaveValue('')
  await editor.getByRole('button', { name: '复盘与标记' }).click()
  await expect(editor.getByLabel('这次为什么出错？')).toHaveValue('')
  await expect(editor.getByLabel('标签')).toHaveValue('')
  await expect(editor.getByRole('button', { name: '较难', exact: true })).toHaveClass(/active/)
  await editor.getByRole('button', { name: '题目与答案' }).click()
  await editor.getByLabel('标题').fill('连续录题的第二道')
  await editor.getByLabel('问题 / 题干', { exact: true }).fill('第二道题的题干')
  await editor.getByRole('button', { name: '关闭', exact: true }).click()
  await openEditor(page, true)
  await editor.getByRole('button', { name: '恢复内容' }).click()
  await expect(editor.getByLabel('标题')).toHaveValue('连续录题的第二道')
  await editor.getByLabel('答案 / 解析', { exact: true }).fill('第二道题的答案')
  await editor.getByRole('button', { name: '收进知识库' }).click()
  await expect(editor).not.toBeVisible()
  const records = await (await page.request.get('/api/v1/items')).json()
  expect(records.total).toBe(2)
  expect(records.items.every((value: { subject: string; chapter_id: string }) => value.subject === 'math' && value.chapter_id === chapter.id)).toBe(true)
  await page.reload()
  await openEditor(page)
  await expect(editor.getByRole('button', { name: '数学', exact: true })).toHaveClass(/selected/)
  await expect(editor.getByRole('combobox', { name: '章节', exact: true })).toHaveValue(chapter.id)
  expect(await page.evaluate(id => localStorage.getItem(`shiyi-draft-${id}`), user.id)).toBeNull()
})

test('图片框选与旋转生成正确像素，失败可重试且共享原图保持不变', async ({ page }) => {
  await account(page)
  await openEditor(page, true)
  const editor = page.locator('.editor-modal')
  await editor.getByLabel('标题').fill('裁剪后的图片错题')
  await editor.getByLabel('答案 / 解析', { exact: true }).fill('裁剪保留左半张，然后顺时针旋转。')
  const uploaded = page.waitForResponse(response => response.url().endsWith('/api/v1/media') && response.request().method() === 'POST')
  await editor.getByLabel('问题 / 题干附件', { exact: true }).setInputFiles({ name: 'crop-grid.png', mimeType: 'image/png', buffer: readFileSync(new URL('./fixtures/crop-grid.png', import.meta.url)) })
  const original = await (await uploaded).json()
  const originalBytes = await (await page.request.get(original.url)).body()
  const shared = await item(page, { title: '另一题共用原图', question_media: [original.id] })
  await editor.getByRole('button', { name: '编辑问题 / 题干图片 1' }).click()
  const crop = page.getByRole('dialog', { name: '裁剪与旋转图片' })
  await expect(crop.getByText('保留约 400 × 240 像素')).toBeVisible()
  await expect(editor.getByRole('button', { name: '收进知识库' })).toBeDisabled()
  const bounds = (await crop.locator('.crop-stage').boundingBox())!
  await page.mouse.move(bounds.x + bounds.width * .15, bounds.y + bounds.height * .15)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width * .8, bounds.y + bounds.height * .8, { steps: 8 })
  await page.mouse.up()
  await expect(crop.locator('.crop-dimensions')).not.toHaveText('保留约 400 × 240 像素')
  await crop.getByRole('button', { name: '重置', exact: true }).click()
  await crop.getByText('精确调整裁剪范围').click()
  await crop.getByLabel('右侧裁去（%）').fill('50')
  await crop.getByRole('button', { name: '向右旋转 90 度' }).click()
  await expect(crop.getByText('保留约 240 × 200 像素')).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('image-crop.png'), fullPage: true, animations: 'disabled' })
  let fail = true
  await page.route('**/api/v1/media', async route => {
    if (route.request().method() === 'POST' && fail) { fail = false; await route.abort('failed') }
    else await route.continue()
  })
  await crop.getByRole('button', { name: '应用修改' }).click()
  await expect(page.getByText(/连接暂时中断/)).toBeVisible()
  await expect(crop).toBeVisible()
  await expect(editor.getByAltText('问题 / 题干图片 1')).toHaveAttribute('src', original.url)
  const changed = page.waitForResponse(response => response.url().endsWith('/api/v1/media') && response.status() === 201)
  await crop.getByRole('button', { name: '应用修改' }).click()
  const replacement = await (await changed).json()
  expect(replacement.width).toBe(240)
  expect(replacement.height).toBe(200)
  expect(replacement.id).not.toBe(original.id)
  await expect(crop).not.toBeVisible()
  const pixels = await page.evaluate(async url => {
    const image = new Image(); image.src = url; await image.decode()
    const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight
    const context = canvas.getContext('2d')!; context.drawImage(image, 0, 0)
    return { left: Array.from(context.getImageData(30, 100, 1, 1).data), right: Array.from(context.getImageData(210, 100, 1, 1).data) }
  }, replacement.url)
  expect(pixels.left[2]).toBeGreaterThan(pixels.left[0] + 60)
  expect(pixels.right[0]).toBeGreaterThan(pixels.right[2] + 80)
  expect((await (await page.request.get(original.url)).body()).equals(originalBytes)).toBe(true)
  expect((await (await page.request.get(`/api/v1/items/${shared.id}`)).json()).question_media[0].id).toBe(original.id)
  await editor.getByRole('button', { name: '编辑问题 / 题干图片 1' }).click()
  await crop.getByRole('button', { name: '向左旋转 90 度' }).click()
  await crop.getByRole('button', { name: '取消', exact: true }).click()
  await expect(editor.getByAltText('问题 / 题干图片 1')).toHaveAttribute('src', replacement.url)
  await editor.getByRole('button', { name: '收进知识库' }).click()
  await expect(editor).not.toBeVisible()
  const saved = await (await page.request.get('/api/v1/items?q=裁剪后的图片错题')).json()
  expect(saved.items[0].question_media[0].id).toBe(replacement.id)
})
