import { expect, test, type Page } from '@playwright/test'
import { account, item, openEditor } from './helpers'

const blocker = '不会根据块大小和路数划分组索引位。'
const ratings = ['忘记', '困难', '良好', '轻松']

async function problem(page: Page, title = '整题反馈 · Cache 地址划分') {
  return item(page, { title, kind: 'problem' })
}

async function reveal(page: Page, id: string) {
  await page.goto(`/review?item=${id}`)
  await page.getByRole('button', { name: /查看答案/ }).click()
  await expect(page.locator('.revealed-answer')).toBeVisible()
}

async function recordFailure(page: Page, record: { id: string; version: number; schedule: { version: number } }, note = blocker) {
  const response = await page.request.post(`/api/v1/items/${record.id}/reviews`, { data: {
    rating: 'again', expected_version: record.schedule.version, expected_item_version: record.version,
    independent_completed: false, blocker: note,
  } })
  expect(response.ok()).toBeTruthy()
}

async function assertNoHorizontalOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
}

test.describe('复习反馈', () => {
  test('整题查看答案后必须明确选择独立完成，按钮和快捷键都受保护', async ({ page }) => {
    await account(page)
    const record = await problem(page)
    await page.goto(`/review?item=${record.id}`)
    await expect(page.getByRole('group', { name: '这次是否独立完成整题？' })).toHaveCount(0)
    await page.getByRole('button', { name: /查看答案/ }).click()
    await expect(page.getByRole('group', { name: '这次是否独立完成整题？' })).toBeVisible()
    for (const label of ratings) await expect(page.getByRole('button', { name: new RegExp(label) })).toBeDisabled()
    await page.locator('h1').click()
    for (const key of ['1', '2', '3', '4']) await page.keyboard.press(key)
    expect((await (await page.request.get(`/api/v1/items/${record.id}/reviews`)).json()).total).toBe(0)
    await assertNoHorizontalOverflow(page)
  })

  test('未独立完成必填主要卡点，只允许忘记；暂停后反馈保留', async ({ page }) => {
    await account(page)
    const record = await problem(page)
    await reveal(page, record.id)
    await page.getByRole('radio', { name: '未独立完成' }).check()
    const note = page.getByLabel('主要卡点', { exact: true })
    await expect(note).toBeVisible()
    await expect(note).toHaveAttribute('maxlength', '2000')
    await expect(page.getByRole('button', { name: /忘记/ })).toBeDisabled()
    await note.fill('   ')
    await expect(page.getByRole('button', { name: /忘记/ })).toBeDisabled()
    await note.fill(blocker)
    await expect(page.getByRole('button', { name: /忘记/ })).toBeEnabled()
    for (const label of ratings.slice(1)) await expect(page.getByRole('button', { name: new RegExp(label) })).toBeDisabled()
    await page.locator('h1').click()
    await page.keyboard.press('3')
    expect((await (await page.request.get(`/api/v1/items/${record.id}/reviews`)).json()).total).toBe(0)
    await page.getByRole('button', { name: '休息一下', exact: true }).click()
    await page.getByRole('button', { name: '继续复习', exact: true }).click()
    await expect(page.getByRole('radio', { name: '未独立完成' })).toBeChecked()
    await expect(note).toHaveValue(blocker)
    await assertNoHorizontalOverflow(page)
  })

  test('保存未完成和卡点，忘记困难显示明天而良好仍可十分钟', async ({ page }) => {
    await account(page)
    const record = await problem(page)
    await reveal(page, record.id)
    await page.getByRole('radio', { name: '未独立完成' }).check()
    await page.getByLabel('主要卡点', { exact: true }).fill(` ${blocker} `)
    await expect(page.getByRole('button', { name: /忘记/ })).toContainText('明天')
    await expect(page.getByRole('button', { name: /困难/ })).toContainText('明天')
    await expect(page.getByRole('button', { name: /良好/ })).toContainText('10 分钟')
    await expect(page.getByText('只有「忘记 / 困难」的短间隔移到明天；「良好」仍可能在 10 分钟后复习。')).toBeVisible()
    await page.screenshot({ path: test.info().outputPath('problem-feedback.png'), fullPage: true, animations: 'disabled' })
    const request = page.waitForRequest(req => req.url().endsWith(`/items/${record.id}/reviews`) && req.method() === 'POST')
    await page.getByRole('button', { name: /忘记/ }).click()
    expect((await request).postDataJSON()).toMatchObject({ expected_item_version: record.version, independent_completed: false, blocker, rating: 'again' })
    await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
    await expect(page.getByText(/卡点已保存/)).toBeVisible()
    const history = await (await page.request.get(`/api/v1/items/${record.id}/reviews`)).json()
    expect(history.items[0]).toMatchObject({ independent_completed: false, blocker, rating: 1 })
    const next = await (await page.request.get(`/api/v1/items/${record.id}`)).json()
    const learningDay = (value: string) => new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai' }).format(new Date(value))
    expect(learningDay(next.schedule.due)).not.toBe(learningDay(history.items[0].reviewed_at))
    await page.getByRole('link', { name: '查看卡点与详情' }).click()
    await expect(page.locator('.history-entry').first()).toContainText('未独立完成')
    await expect(page.locator('.history-entry').first()).toContainText(blocker)
  })

  for (const [rating, label, value] of [['hard', '困难', 2], ['good', '良好', 3], ['easy', '轻松', 4]] as const) {
    test(`独立完成可选${label}，不能选忘记，保存明确成功记录`, async ({ page }) => {
      await account(page)
      const record = await problem(page)
      await reveal(page, record.id)
      await page.getByRole('radio', { name: '未独立完成' }).check()
      await page.getByLabel('主要卡点', { exact: true }).fill('切换为独立完成后不能误存这段卡点。')
      await page.getByRole('radio', { name: '已独立完成', exact: true }).check()
      await expect(page.getByRole('button', { name: /忘记/ })).toBeDisabled()
      for (const success of ratings.slice(1)) await expect(page.getByRole('button', { name: new RegExp(success) })).toBeEnabled()
      const request = page.waitForRequest(req => req.url().endsWith(`/items/${record.id}/reviews`) && req.method() === 'POST')
      await page.getByRole('button', { name: new RegExp(label) }).click()
      expect((await request).postDataJSON()).toMatchObject({ rating, independent_completed: true, blocker: '', expected_item_version: record.version })
      await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
      await page.goto(`/items/${record.id}`)
      await expect(page.locator('.history-entry').first()).toContainText('已独立完成')
      const history = await (await page.request.get(`/api/v1/items/${record.id}/reviews`)).json()
      expect(history.items[0]).toMatchObject({ independent_completed: true, blocker: '', rating: value })
    })
  }

  test('从历史卡点提炼小任务，来源自动关联且学习状态与评分独立', async ({ page }) => {
    await account(page)
    const record = await problem(page)
    await recordFailure(page, record)
    const sourceBefore = await (await page.request.get(`/api/v1/items/${record.id}`)).json()
    await page.goto(`/items/${record.id}`)
    await page.getByRole('button', { name: '提炼小任务' }).click()
    const editor = page.getByRole('dialog', { name: '从卡点提炼小任务' })
    await expect(editor.getByText(record.title, { exact: true })).toBeVisible()
    await expect(editor.getByLabel('内容类型')).toHaveValue('concept')
    await expect(editor.getByLabel('问题 / 题干', { exact: true })).toHaveValue(new RegExp(blocker))
    await expect(editor.getByLabel('答案 / 解析', { exact: true })).toHaveValue('')
    await editor.getByLabel('标题').fill('独立小任务 · 如何计算组索引位数')
    await editor.getByLabel('问题 / 题干', { exact: true }).fill('已知 Cache 组数，如何计算组索引位数？')
    await editor.getByLabel('答案 / 解析', { exact: true }).fill('组索引位数 = log₂(组数)。')
    await editor.getByRole('button', { name: '收进知识库' }).click()
    await expect(editor).not.toBeVisible()
    const related = page.getByRole('region', { name: '关联小任务' })
    await expect(related.getByRole('link', { name: '独立小任务 · 如何计算组索引位数', exact: true })).toBeVisible()
    const tasks = await (await page.request.get(`/api/v1/items?source_item_id=${record.id}`)).json()
    expect(tasks.total).toBe(1)
    const task = tasks.items[0]
    expect(task).toMatchObject({ source_item_id: record.id, kind: 'concept', schedule: { state: 'new', version: 0, last_review: null } })
    await related.getByRole('link', { name: task.title, exact: true }).click()
    await expect(page.getByRole('link', { name: '查看来源原题' })).toHaveAttribute('href', `/items/${record.id}`)
    await page.getByRole('link', { name: '查看来源原题' }).click()
    await related.getByRole('link', { name: `复习 ${task.title}`, exact: true }).click()
    await page.getByRole('button', { name: /查看答案/ }).click()
    await expect(page.getByRole('group', { name: '这次是否独立完成整题？' })).toHaveCount(0)
    await page.getByRole('button', { name: /良好/ }).click()
    await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
    const sourceAfter = await (await page.request.get(`/api/v1/items/${record.id}`)).json()
    expect(sourceAfter.schedule).toEqual(sourceBefore.schedule)
    expect((await (await page.request.get(`/api/v1/items/${record.id}/reviews`)).json()).total).toBe(1)
    await assertNoHorizontalOverflow(page)
  })

  test('派生小任务可留空答案存草稿，本机草稿按原题隔离', async ({ page }) => {
    await account(page)
    const first = await problem(page, '原题甲')
    const second = await problem(page, '原题乙')
    await recordFailure(page, first)
    await recordFailure(page, second, '第二题的独立卡点')
    const normal = await openEditor(page)
    await normal.getByLabel('标题').fill('普通录入未保存草稿')
    await normal.getByRole('button', { name: '关闭', exact: true }).click()
    await page.goto(`/items/${first.id}`)
    await page.getByRole('button', { name: '提炼小任务' }).click()
    const editor = page.getByRole('dialog')
    await expect(editor.getByRole('button', { name: '恢复内容' })).toHaveCount(0)
    await editor.getByLabel('标题').fill('原题甲的小任务草稿')
    await editor.getByRole('button', { name: '关闭', exact: true }).click()
    await page.goto(`/items/${second.id}`)
    await page.getByRole('button', { name: '提炼小任务' }).click()
    await expect(editor.getByRole('button', { name: '恢复内容' })).toHaveCount(0)
    await expect(editor.getByLabel('问题 / 题干', { exact: true })).toHaveValue(/第二题的独立卡点/)
    await editor.getByRole('button', { name: '关闭', exact: true }).click()
    await page.goto(`/items/${first.id}`)
    await page.getByRole('button', { name: '提炼小任务' }).click()
    await editor.getByRole('button', { name: '恢复内容' }).click()
    await expect(editor.getByLabel('标题')).toHaveValue('原题甲的小任务草稿')
    await expect(editor.getByLabel('答案 / 解析', { exact: true })).toHaveValue('')
    await editor.getByRole('button', { name: '存为草稿' }).click()
    await expect(editor).not.toBeVisible()
    const result = await (await page.request.get(`/api/v1/items?source_item_id=${first.id}&status=draft`)).json()
    expect(result.total).toBe(1)
    expect(result.items[0]).toMatchObject({ source_item_id: first.id, status: 'draft' })
    const draft = await (await page.request.get(`/api/v1/items/${result.items[0].id}`)).json()
    expect(draft.answer).toBe('')
    await openEditor(page)
    await editor.getByRole('button', { name: '恢复内容' }).click()
    await expect(editor.getByLabel('标题')).toHaveValue('普通录入未保存草稿')
  })

  test('未确认保存时冻结反馈并原样重试，不重复评分', async ({ page }) => {
    await account(page)
    const record = await problem(page)
    const payloads: unknown[] = []
    await page.route(`**/api/v1/items/${record.id}/reviews`, async route => {
      if (route.request().method() !== 'POST') return route.continue()
      payloads.push(route.request().postDataJSON())
      if (payloads.length === 1) { await route.fetch(); await route.abort('failed') }
      else await route.continue()
    })
    await reveal(page, record.id)
    await page.getByRole('radio', { name: '未独立完成' }).check()
    await page.getByLabel('主要卡点', { exact: true }).fill(blocker)
    await page.getByRole('button', { name: /忘记/ }).click()
    await expect(page.getByRole('button', { name: '重试保存' })).toBeVisible()
    await expect(page.getByLabel('主要卡点', { exact: true })).toBeDisabled()
    await expect(page.getByRole('radio', { name: '已独立完成', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: '暂时跳过' })).toBeDisabled()
    await expect(page.getByRole('button', { name: '休息一下', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: '重试保存' }).click()
    await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
    expect(payloads).toHaveLength(2)
    expect(payloads[1]).toEqual(payloads[0])
    expect((await (await page.request.get(`/api/v1/items/${record.id}/reviews`)).json()).total).toBe(1)
  })

  test('修改整题内容后必须重新查看答案和填写反馈，不能沿用旧题尝试', async ({ page }) => {
    await account(page)
    const record = await problem(page)
    await reveal(page, record.id)
    await page.getByRole('radio', { name: '未独立完成' }).check()
    await page.getByLabel('主要卡点', { exact: true }).fill(blocker)
    await page.getByRole('button', { name: '编辑这条内容' }).click()
    const editor = page.getByRole('dialog')
    await editor.getByLabel('标题').fill('已重新整理的整题')
    await editor.getByRole('button', { name: '保存修改' }).click()
    await expect(editor).not.toBeVisible()
    await expect(page.getByRole('heading', { name: '已重新整理的整题' })).toBeVisible()
    await expect(page.getByRole('button', { name: /查看答案/ })).toBeVisible()
    await expect(page.getByRole('group', { name: '这次是否独立完成整题？' })).toHaveCount(0)
    await page.getByRole('button', { name: /查看答案/ }).click()
    for (const label of ratings) await expect(page.getByRole('button', { name: new RegExp(label) })).toBeDisabled()
    await page.getByRole('radio', { name: '已独立完成', exact: true }).check()
    await page.getByRole('button', { name: /良好/ }).click()
    await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
  })

  test('旧记录显示未记录独立完成，不把未知历史算作失败', async ({ page }) => {
    await account(page)
    const record = await problem(page)
    expect((await page.request.post(`/api/v1/items/${record.id}/reviews`, { data: { rating: 'good', expected_version: 0 } })).ok()).toBeTruthy()
    await page.goto(`/items/${record.id}`)
    await expect(page.locator('.history-entry').first()).toContainText('未记录独立完成情况')
    await expect(page.getByRole('button', { name: '提炼小任务' })).toHaveCount(0)
  })
})
