import { expect, test } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import { account, item, openEditor, password, picture } from './helpers'

test('网页创建账号、退出和重新登录', async ({ page }) => {
  const username = 'owner-' + randomUUID().slice(0, 8)
  await page.goto('/login')
  await expect(page.getByLabel('用户名')).toBeVisible()
  if (await page.getByRole('button', { name: '创建一个独立的学习账号' }).isVisible()) {
    await page.getByRole('button', { name: '创建一个独立的学习账号' }).click()
  }
  await page.getByLabel('怎么称呼你').fill('拾忆同学')
  await page.getByLabel('用户名').fill(username)
  await page.locator('input[autocomplete="new-password"]').fill(password)
  await page.getByRole('button', { name: '开始我的积累' }).click()
  await expect(page.getByRole('heading', { name: /拾忆同学/ })).toBeVisible()
  await expect(page.getByRole('button', { name: '记录第一条知识' })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('dashboard-empty.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: '退出登录' }).click()
  await expect(page.getByRole('heading', { name: '欢迎回来。' })).toBeVisible()
  await page.getByLabel('用户名').fill(username)
  await page.locator('input[autocomplete="current-password"]').fill(password)
  await page.getByRole('button', { name: '进入学习空间' }).click()
  await expect(page.getByRole('heading', { name: /拾忆同学/ })).toBeVisible()
})

test('图片错题的录入、评分、撤销、编辑、暂停与恢复', async ({ page }) => {
  await account(page)
  const editor = await openEditor(page, true)
  await editor.getByRole('button', { name: '数学', exact: true }).click()
  await editor.getByLabel('标题').fill('用定义求平方函数的导数')
  await editor.getByLabel('问题 / 题干附件', { exact: true }).setInputFiles(picture)
  await expect(editor.getByAltText('问题 / 题干图片 1')).toBeVisible()
  await editor.getByLabel('答案 / 解析', { exact: true }).fill("由定义可得：$f'(x)=2x$。先展开平方，再约去 $h$。")
  await editor.getByRole('button', { name: '复盘与标记' }).click()
  await editor.getByRole('button', { name: '较难', exact: true }).click()
  await editor.getByLabel('这次为什么出错？').fill('忘记展开平方中的交叉项。')
  await editor.getByLabel('留给下次自己的提醒').fill('先完整展开，再约分。')
  await editor.getByLabel('标签').fill('导数定义，易错题')
  await editor.getByRole('button', { name: '收进知识库' }).click()
  await expect(editor).not.toBeVisible()
  await page.getByRole('link').filter({ hasText: '用定义求平方函数的导数' }).click()
  await expect(page.getByRole('heading', { name: '用定义求平方函数的导数' })).toBeVisible()
  await expect(page.locator('.katex').first()).toBeVisible()
  await page.getByRole('button', { name: '放大图片 1' }).click()
  await expect(page.getByRole('dialog', { name: '图片 1 / 1' })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  const id = page.url().split('/').at(-1)!
  await page.getByRole('link', { name: '复习这条知识' }).click()
  await expect(page.locator('.revealed-answer')).toHaveCount(0)
  await page.getByRole('button', { name: /记录我的解答/ }).click()
  await page.getByLabel('我的解答', { exact: true }).fill('展开 (x+h)² - x²，再除以 h，得到 2x+h。')
  await page.getByLabel('我的解答附件', { exact: true }).setInputFiles(picture)
  await expect(page.getByAltText('我的解答图片 1')).toBeVisible()
  await page.getByRole('button', { name: '休息一下', exact: true }).click()
  await page.getByRole('button', { name: '继续复习', exact: true }).click()
  await expect(page.getByLabel('我的解答', { exact: true })).toHaveValue(/展开/)
  await page.getByRole('button', { name: /查看答案/ }).click()
  await expect(page.locator('.revealed-answer .katex').first()).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('review-with-image.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: /良好/ }).click()
  await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
  let history = await (await page.request.get(`/api/v1/items/${id}/reviews`)).json()
  expect(history.total).toBe(1)
  expect(history.items[0].answer_media).toHaveLength(1)
  let finishUndoRefresh!: () => void
  const undoRefresh = new Promise<void>(resolve => { finishUndoRefresh = resolve })
  await page.route(`**/api/v1/items/${id}`, async route => { await undoRefresh; await route.continue() })
  await page.getByRole('button', { name: '撤销上次评分' }).click()
  try { await expect(page.getByText('正在翻开下一条记忆…')).toBeVisible() }
  finally { finishUndoRefresh() }
  await expect(page.getByRole('heading', { name: '用定义求平方函数的导数' })).toBeVisible()
  await page.getByRole('button', { name: /查看答案/ }).click()
  await page.getByRole('button', { name: /轻松/ }).click()
  await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
  history = await (await page.request.get(`/api/v1/items/${id}/reviews`)).json()
  expect(history.total).toBe(2)
  expect(history.items.filter((review: { undone: boolean }) => !review.undone)).toHaveLength(1)
  const before = await (await page.request.get(`/api/v1/items/${id}`)).json()
  await page.goto(`/items/${id}`)
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByRole('dialog').getByLabel('标题').fill('平方函数求导 · 已整理')
  await page.getByRole('button', { name: '保存修改' }).click()
  await expect(page.getByRole('heading', { name: '平方函数求导 · 已整理' })).toBeVisible()
  const after = await (await page.request.get(`/api/v1/items/${id}`)).json()
  expect(after.schedule.version).toBe(before.schedule.version)
  expect(after.schedule.due).toBe(before.schedule.due)
  await page.getByRole('button', { name: '暂停复习', exact: true }).click()
  await expect(page.getByText('复习已暂停', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '恢复复习', exact: true }).click()
  await expect(page.getByRole('link', { name: '复习这条知识' })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '移入回收站', exact: true }).click()
  await expect(page).toHaveURL(/\/library$/)
  await page.getByRole('button', { name: '筛选', exact: true }).click()
  await page.getByRole('combobox', { name: /内容状态/ }).selectOption('deleted')
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(page.getByText('已恢复内容与学习进度')).toBeVisible()
  const restored = await (await page.request.get(`/api/v1/items/${id}`)).json()
  expect(restored.status).toBe('active')
  expect(restored.schedule.due).toBe(before.schedule.due)
})

test('上传完成前禁止保存，关闭后立即恢复未保存内容', async ({ page }) => {
  await account(page)
  const editor = await openEditor(page)
  await editor.getByLabel('标题').fill('图片上传保护')
  await editor.getByLabel('答案 / 解析', { exact: true }).fill('图片中的题目答案。')
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/v1/media', async route => { await gate; await route.continue() })
  await editor.getByLabel('问题 / 题干附件', { exact: true }).setInputFiles(picture)
  await expect(editor.getByRole('button', { name: '收进知识库' })).toBeDisabled()
  await expect(editor.getByRole('button', { name: '存为草稿' })).toBeDisabled()
  await editor.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(editor).toBeVisible()
  release()
  await expect(editor.getByAltText('问题 / 题干图片 1')).toBeVisible()
  await editor.getByLabel('标题').fill('关闭前刚输入的标题')
  await editor.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '记录新知', exact: true }).last().click()
  await page.getByRole('button', { name: '恢复内容', exact: true }).click()
  await expect(editor.getByLabel('标题')).toHaveValue('关闭前刚输入的标题')
  await expect(editor.getByAltText('问题 / 题干图片 1')).toBeVisible()
  await editor.getByRole('button', { name: '收进知识库' }).click()
  await expect(editor).not.toBeVisible()
  const result = await (await page.request.get('/api/v1/items')).json()
  expect(result.items[0].question_media).toHaveLength(1)
})

test('队列刷新和暂停不会切题或清除解答，暂停不计入用时', async ({ page }) => {
  await account(page)
  const first = await item(page, { title: '正在独立回忆的题目' })
  await item(page, { title: '队列里另一道题目' })
  let reverse = false
  await page.route('**/api/v1/reviews/due*', async route => {
    const response = await route.fetch()
    const data = await response.json()
    if (reverse) data.items.reverse()
    await route.fulfill({ response, json: data })
  })
  await page.clock.install()
  await page.goto('/review')
  await expect(page.getByRole('heading', { name: first.title })).toBeVisible()
  await page.getByRole('button', { name: /记录我的解答/ }).click()
  await page.getByLabel('我的解答', { exact: true }).fill('正在写的思路不会消失。')
  reverse = true
  const refresh = page.waitForResponse(response => response.url().includes('/reviews/due'))
  await page.clock.fastForward(31_000)
  await refresh
  await expect(page.getByRole('heading', { name: first.title })).toBeVisible()
  await expect(page.getByLabel('我的解答', { exact: true })).toHaveValue('正在写的思路不会消失。')
  await page.getByRole('button', { name: '休息一下', exact: true }).click()
  await page.clock.fastForward(180_000)
  await page.getByRole('button', { name: '继续复习', exact: true }).click()
  await expect(page.getByLabel('我的解答', { exact: true })).toHaveValue('正在写的思路不会消失。')
  await page.getByRole('button', { name: /查看答案/ }).click()
  await page.getByRole('button', { name: /良好/ }).click()
  await expect(page.getByRole('heading', { name: '队列里另一道题目' })).toBeVisible()
  const history = await (await page.request.get(`/api/v1/items/${first.id}/reviews`)).json()
  expect(history.items[0].duration_ms).toBeLessThan(90_000)
  expect(history.items[0].answer_text).toBe('正在写的思路不会消失。')
})

test('保存结果不确定时沿用同一请求重试，不重复评分', async ({ page }) => {
  await account(page)
  const record = await item(page)
  let interrupted = false
  await page.route(`**/api/v1/items/${record.id}/reviews`, async route => {
    if (route.request().method() === 'POST' && !interrupted) {
      interrupted = true
      await route.fetch()
      await route.abort('failed')
    } else await route.continue()
  })
  await page.goto(`/review?item=${record.id}`)
  await page.getByRole('button', { name: /查看答案/ }).click()
  await page.getByRole('button', { name: /良好/ }).click()
  await expect(page.getByRole('button', { name: '重试保存' })).toBeVisible()
  await page.getByRole('button', { name: '重试保存' }).click()
  await expect(page.getByText('今天的努力，已悄悄生根。')).toBeVisible()
  expect((await (await page.request.get(`/api/v1/items/${record.id}/reviews`)).json()).total).toBe(1)
})

test('设置页创建 API 密钥，外部请求执行 CRUD，撤销后失效', async ({ page }) => {
  await account(page)
  await page.goto('/settings?tab=api')
  await page.getByRole('button', { name: '创建密钥', exact: true }).click()
  await page.getByLabel('给连接起个名字').fill('自动化测试连接')
  await page.getByRole('dialog').getByRole('button', { name: '创建密钥', exact: true }).click()
  const token = await page.locator('.new-token code').innerText()
  expect(token.startsWith('sy_')).toBe(true)
  await page.getByRole('button', { name: '我已保存' }).click()
  const headers = { Authorization: `Bearer ${token}` }
  const created = await page.request.post('/api/v1/items', { headers, data: { title: 'API 新建单词', subject: 'english', question: 'recall', answer: '回忆', kind: 'vocabulary', external_id: 'test:word:1' } })
  expect(created.status()).toBe(201)
  const record = await created.json()
  expect((await page.request.get('/api/v1/items?external_id=test:word:1', { headers })).status()).toBe(200)
  const updated = await page.request.patch(`/api/v1/items/${record.id}`, { headers, data: { difficulty: 'hard', expected_version: record.version } })
  expect((await updated.json()).difficulty).toBe('hard')
  expect((await page.request.delete(`/api/v1/items/${record.id}`, { headers })).status()).toBe(204)
  expect((await page.request.post(`/api/v1/items/${record.id}/restore`, { headers })).status()).toBe(200)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByText('密钥已撤销')).toBeVisible()
  expect((await page.request.get('/api/v1/items', { headers })).status()).toBe(401)
})

test('网页备份携带图片和复习状态，重复导入不增加条目', async ({ page }) => {
  await account(page)
  const uploaded = await page.request.post('/api/v1/media', { multipart: { file: picture } })
  expect(uploaded.status()).toBe(201)
  const media = await uploaded.json()
  const record = await item(page, { question_media: [media.id], is_mistake: true })
  await page.request.post(`/api/v1/items/${record.id}/reviews`, { data: { rating: 'easy', expected_version: 0 } })
  const original = await (await page.request.get(`/api/v1/items/${record.id}`)).json()
  await page.goto('/settings?tab=data')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载备份 ZIP' }).click()
  const saved = await download
  const archive = await readFile((await saved.path())!)
  for (const duplicate of [false, true]) {
    page.once('dialog', dialog => dialog.accept())
    await page.locator('input[type=file]').setInputFiles({ name: 'shiyi-backup.zip', mimeType: 'application/zip', buffer: archive })
    await expect(page.getByText(duplicate ? '这份备份已经导入过，没有重复添加' : '已导入 1 条内容及关联记录')).toBeVisible()
    const list = await (await page.request.get('/api/v1/items')).json()
    expect(list.total).toBe(2)
    const imported = list.items.find((entry: { id: string }) => entry.id !== record.id)
    expect(imported.question_media).toHaveLength(1)
    expect(imported.schedule.due).toBe(original.schedule.due)
  }
})

test('中文检索、难度筛选、章节和学习偏好可保存', async ({ page }) => {
  await account(page)
  await item(page, { title: '矩阵的秩', subject: 'math', difficulty: 'hard', tags: ['线性代数'] })
  await item(page, { title: 'TCP 三次握手', difficulty: 'basic' })
  await item(page, { title: 'recall 的用法', subject: 'english', kind: 'vocabulary' })
  await page.goto('/library')
  await page.getByLabel('搜索知识库').fill('线性代数')
  await expect(page.locator('.knowledge-card')).toHaveCount(1)
  await expect(page.locator('.knowledge-card')).toContainText('矩阵的秩')
  await page.getByRole('button', { name: '清空', exact: true }).click()
  await expect(page.locator('.knowledge-card')).toHaveCount(3)
  await page.getByLabel('选择 矩阵的秩').check()
  await page.getByRole('button', { name: '英语', exact: true }).click()
  await expect(page.locator('.selection-actions')).toHaveCount(0)
  await page.getByRole('button', { name: '全部科目', exact: true }).click()
  await page.getByRole('button', { name: '筛选', exact: true }).click()
  await page.getByLabel('题目难度').selectOption('hard')
  await expect(page.locator('.knowledge-card')).toHaveCount(1)
  await page.goto('/settings?tab=learning')
  await page.getByLabel('每天希望完成的复习次数').fill('20')
  await page.getByLabel('每天最多学习的新内容').fill('0')
  await page.getByRole('button', { name: '保存偏好' }).click()
  await expect(page.getByText('已保存，按你的节奏来')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('每天希望完成的复习次数')).toHaveValue('20')
  expect((await (await page.request.get('/api/v1/reviews/due')).json()).new_available).toBe(0)
  await page.getByRole('button', { name: '科目与章节', exact: true }).click()
  await page.getByRole('button', { name: '添加章节', exact: true }).first().click()
  await page.getByLabel('章节名称').fill('综合错题')
  await page.getByRole('button', { name: '保存章节' }).click()
  await expect(page.locator('.chapter-list').getByText('综合错题')).toBeVisible()
  await page.getByRole('button', { name: '重命名综合错题' }).click()
  await page.getByLabel('章节名称').fill('综合复习')
  await page.getByRole('button', { name: '保存章节' }).click()
  await expect(page.locator('.chapter-list').getByText('综合复习')).toBeVisible()
  await page.goto('/statistics')
  await expect(page.getByRole('heading', { name: '认真过的日子，有迹可循。' })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('statistics.png'), fullPage: true, animations: 'disabled' })
})
