import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, BookOpen, Clock3, History, Pause, Pencil, Play, RotateCcw, Trash2 } from 'lucide-react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { api, patch, post, refreshLearning } from '../api'
import { dateLabel, difficultyNames, ratingNames, relativeDue, stateNames, subjectName } from '../lib'
import type { Item, Review } from '../types'
import { useEditor } from '../components/Editor'
import { Content, Empty, ErrorState, Loading } from '../components/ui'

export default function ItemDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const location = useLocation()
  const edit = useEditor()
  const [historyPage, setHistoryPage] = useState(1)
  const item = useQuery({ queryKey: ['item', id], queryFn: () => api<Item>(`/items/${id}`) })
  const history = useQuery({ queryKey: ['history', id, historyPage], queryFn: () => api<{ items: Review[]; total: number }>(`/items/${id}/reviews?page=${historyPage}`) })
  if (item.isPending) return <Loading/>
  if (item.error) return <ErrorState error={item.error} retry={() => void item.refetch()}/>
  const data = item.data
  const returnTo = typeof location.state?.returnTo === 'string' && /^\/(?:library|mistakes)(?:\?|$)/.test(location.state.returnTo) ? location.state.returnTo : null
  const backTo = returnTo ?? (data.is_mistake ? '/mistakes' : '/library')
  const changeStatus = async () => { try { await patch(`/items/${id}`, { status: data.status === 'suspended' ? 'active' : 'suspended', expected_version: data.version }); refreshLearning(); toast.success(data.status === 'suspended' ? '已恢复复习' : '已暂停，历史记录会保留') } catch (e) { toast.error((e as Error).message) } }
  return <div className="detail-page page-enter"><Link className="back-link" to={backTo}><ArrowLeft size={16}/>回到{backTo.startsWith('/mistakes') ? '错题本' : '知识库'}</Link><div className="detail-heading"><div><div className="eyebrow">{subjectName(data.subject)} / {difficultyNames[data.difficulty]}</div><h1>{data.title}</h1><div className="detail-tags">{data.tags.map(t => <span key={t}>#{t}</span>)}</div></div><div className="detail-actions">{data.status !== 'deleted' ? <><button className="button secondary" onClick={() => edit({ item: data })}><Pencil size={16}/>编辑</button>{data.status !== 'draft' && <button className="icon-button" title={data.status === 'suspended' ? '恢复复习' : '暂停复习'} aria-label={data.status === 'suspended' ? '恢复复习' : '暂停复习'} onClick={() => void changeStatus()}>{data.status === 'suspended' ? <Play size={18}/> : <Pause size={18}/>}</button>}<button className="icon-button danger" aria-label="移入回收站" onClick={async () => { if (!window.confirm('将这条内容移入回收站？学习记录会保留。')) return; try { await api(`/items/${id}`, { method: 'DELETE' }); refreshLearning(); navigate(returnTo ?? '/library'); toast.success('已移入回收站') } catch (e) { toast.error((e as Error).message) } }}><Trash2 size={18}/></button></> : <button className="button secondary" onClick={async () => { try { await post(`/items/${id}/restore`); refreshLearning() } catch (e) { toast.error((e as Error).message) } }}><RotateCcw size={16}/>恢复内容</button>}</div></div>
    <div className="detail-layout"><div className="detail-main"><section className="panel detail-content"><div className="content-label"><BookOpen size={16}/>问题与题干</div><Content text={data.question} media={data.question_media}/>{!data.question && !data.question_media.length && <p className="muted">这条草稿还没有题目，点击编辑继续补充。</p>}</section><section className="panel detail-content answer-panel"><div className="content-label"><span className="status-dot"/>答案与解析</div><Content text={data.answer} media={data.answer_media}/>{!data.answer && !data.answer_media?.length && <p className="muted">还没有参考答案。</p>}</section>{data.is_mistake && (data.mistake_reason || data.takeaway) && <section className="reflection-panel"><span className="eyebrow">A NOTE TO MY FUTURE SELF</span>{data.mistake_reason && <><h3>这次为什么出错</h3><Content text={data.mistake_reason}/></>}{data.takeaway && <><h3>留给下次自己的提醒</h3><Content text={data.takeaway}/></>}</section>}{data.source && <p className="source-note">来源：{data.source}</p>}</div>
      <aside className="detail-aside"><section className="panel memory-panel"><h2><Clock3 size={17}/>这条记忆的节奏</h2><div className="memory-due"><span>下次相遇</span><strong>{data.status === 'active' ? relativeDue(data.schedule.due, data.schedule.state === 'new') : data.status === 'draft' ? '等待补充' : data.status === 'deleted' ? '已在回收站' : '复习已暂停'}</strong>{data.schedule.last_review && <small>{dateLabel(data.schedule.due, true)}</small>}</div><dl><div><dt>学习状态</dt><dd>{stateNames[data.schedule.state]}</dd></div><div><dt>最近复习</dt><dd>{dateLabel(data.schedule.last_review)}</dd></div><div><dt>收录时间</dt><dd>{dateLabel(data.created_at)}</dd></div>{data.schedule.retrievability !== null && <div><dt>预计可回忆概率</dt><dd>{Math.round(data.schedule.retrievability * 100)}%</dd></div>}</dl>{data.schedule.retrievability !== null && <p className="field-help">根据复习历史估计，不代表考试掌握程度。</p>}{data.status === 'active' && <Link to={`/review?item=${id}`} className="button primary full-width"><Play size={16}/>复习这条知识</Link>}</section>
      <section className="panel history-panel"><h2><History size={17}/>复习的足迹<span>{history.data?.total ?? 0}</span></h2>{history.isPending ? <Loading text="加载记录…"/> : history.error ? <ErrorState error={history.error}/> : !history.data.items.length ? <Empty title="还没有复习记录" description="第一次认真回忆，就从这里开始。"/> : <><div className="history-list">{history.data.items.map(r => <div key={r.id} className={`history-entry ${r.undone ? 'undone' : ''}`}><span className={`history-dot rating-${r.rating}`}/><div><strong>{ratingNames[r.rating]}{r.undone && <small> · 已撤销</small>}</strong><span>{dateLabel(r.reviewed_at, true)}</span>{r.answer_text && <p>{r.answer_text}</p>}{r.answer_media.length > 0 && <Content media={r.answer_media.map(mid => ({ id: mid, url: `/api/v1/media/${mid}`, filename: '本次解答', width: 0, height: 0, size: 0, mime_type: 'image/webp' }))}/>}</div></div>)}</div>{history.data.total > 30 && <div className="pagination compact"><button className="text-button" disabled={historyPage === 1} onClick={() => setHistoryPage(p => p - 1)}>上一页</button><span>{historyPage}</span><button className="text-button" disabled={historyPage * 30 >= history.data.total} onClick={() => setHistoryPage(p => p + 1)}>下一页</button></div>}</>}</section></aside></div>
  </div>
}
