import { useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { BookOpen, Check, Copy, Download, ExternalLink, KeyRound, LockKeyhole, Pencil, Plus, Save, Settings2, ShieldCheck, Trash2, Upload } from 'lucide-react'
import { useOutletContext, useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'
import { api, post, queryClient, refreshLearning } from '../api'
import { dateLabel, subjects } from '../lib'
import type { APIKey, Chapter, Preferences, Subject, User } from '../types'
import { Empty, ErrorState, Modal, PageHeading, Spinner } from '../components/ui'

export default function Settings() {
  const { user } = useOutletContext<{ user: User }>()
  const [params, setParams] = useSearchParams()
  const tab = params.get('tab') ?? 'learning'
  const tabs = [{ id: 'learning', name: '学习偏好', icon: Settings2 }, { id: 'chapters', name: '科目与章节', icon: BookOpen }, { id: 'api', name: 'API 连接', icon: KeyRound }, { id: 'data', name: '数据与账号', icon: ShieldCheck }]
  return <div className="settings-page page-enter"><PageHeading eyebrow="MAKE ROOM FOR YOUR OWN RHYTHM" title="找到适合自己的节奏。" description="让复习方式贴近你，也让知识始终掌握在自己手里。"/><div className="settings-tabs">{tabs.map(t => <button key={t.id} className={tab === t.id ? 'active' : ''} onClick={() => setParams({ tab: t.id })}><t.icon size={17}/>{t.name}</button>)}</div>{tab === 'learning' ? <LearningSettings user={user}/> : tab === 'chapters' ? <ChapterSettings/> : tab === 'api' ? <APISettings/> : <DataSettings user={user}/>}</div>
}

function LearningSettings({ user }: { user: User }) {
  const [form, setForm] = useState<Preferences>(user.preferences)
  const [busy, setBusy] = useState(false)
  return <form className="settings-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { const updated = await api<User>('/preferences', { method: 'PUT', body: JSON.stringify(form) }); queryClient.setQueryData(['me'], updated); refreshLearning(); toast.success('已保存，按你的节奏来') } catch (e) { toast.error((e as Error).message) } finally { setBusy(false) } }}>
    <section className="panel settings-section"><div className="settings-section-heading"><h2>日常的小目标</h2><p>留出稳定的一点时间，比偶尔的冲刺更容易坚持。</p></div><div className="form-row"><label className="field">每天希望完成的复习次数<input type="number" min={1} max={1000} required value={form.daily_goal} onChange={e => setForm({ ...form, daily_goal: Number(e.target.value) })}/><span className="field-help">用于展示今日进度，不会截断到期复习。</span></label><label className="field">每天最多学习的新内容<input type="number" min={0} max={500} required value={form.daily_new_limit} onChange={e => setForm({ ...form, daily_new_limit: Number(e.target.value) })}/><span className="field-help">三科合计；设为 0 时，专心巩固已学内容。</span></label></div><div className="form-row"><label className="field">你的目标日期<input type="date" value={form.exam_date ?? ''} onChange={e => setForm({ ...form, exam_date: e.target.value || null })}/><span className="field-help">可以是考试日，也可以是自己的阶段目标。</span></label><label className="field">学习时区<select value={form.timezone} onChange={e => setForm({ ...form, timezone: e.target.value })}><option value="Asia/Shanghai">北京时间 · Asia/Shanghai</option><option value="Asia/Tokyo">东京时间 · Asia/Tokyo</option><option value="Europe/London">伦敦时间 · Europe/London</option><option value="America/New_York">纽约时间 · America/New_York</option><option value="America/Los_Angeles">洛杉矶时间 · America/Los_Angeles</option><option value="UTC">协调世界时 · UTC</option></select></label></div></section>
    <section className="panel settings-section"><div className="settings-section-heading"><h2>记住多少，由你选择</h2><p>目标保持率越高，复习会越频繁。90% 是一个平衡的起点。</p></div><div className="retention-settings">{subjects.map(s => <div key={s.id}><span className={`retention-symbol ${s.color}`}>{s.symbol}</span><div><label htmlFor={`retention-${s.id}`}>{s.name}<b>{Math.round(form.retention[s.id] * 100)}%</b></label><input id={`retention-${s.id}`} type="range" min={70} max={97} step={1} value={Math.round(form.retention[s.id] * 100)} onChange={e => setForm({ ...form, retention: { ...form.retention, [s.id]: Number(e.target.value) / 100 } })}/><div className="range-labels"><span>少一些复习</span><span>多一些巩固</span></div></div></div>)}</div><div className="settings-note"><ShieldCheck size={19}/><p>调整后从下一次复习起生效，已有到期时间与历史记录会保留。系统采用 FSRS 默认模型参数，根据每次真实表现更新记忆状态。</p></div></section>
    <div className="settings-save"><span>好的计划，应该给生活留有余地。</span><button className="button primary" disabled={busy}>{busy ? <Spinner/> : <Save size={16}/>}保存偏好</button></div>
  </form>
}

function ChapterSettings() {
  const chapters = useQuery({ queryKey: ['chapters'], queryFn: () => api<Chapter[]>('/chapters') })
  const [editing, setEditing] = useState<{ id?: string; subject: Subject; name: string } | null>(null)
  const [busy, setBusy] = useState(false)
  return <><div className="chapter-settings-grid">{subjects.map(s => <section className="panel chapter-panel" key={s.id}><div className="chapter-heading"><span className={`subject-symbol ${s.color}`}>{s.symbol}</span><div><h2>{s.name}</h2><span>{chapters.data?.filter(c => c.subject === s.id).length ?? 0} 个章节</span></div></div><div className="chapter-list">{chapters.data?.filter(c => c.subject === s.id).map(c => <div key={c.id}><span>{c.name}</span><button className="icon-button" aria-label={`重命名${c.name}`} onClick={() => setEditing(c)}><Pencil size={14}/></button><button className="icon-button danger" aria-label={`删除章节${c.name}`} onClick={async () => { if (!window.confirm(`删除“${c.name}”章节？其中的知识会保留，并变为未分章节。`)) return; try { await api(`/chapters/${c.id}`, { method: 'DELETE' }); refreshLearning(); toast.success('章节已删除，内容已保留') } catch (e) { toast.error((e as Error).message) } }}><Trash2 size={14}/></button></div>)}</div><button className="button secondary full-width" onClick={() => setEditing({ subject: s.id, name: '' })}><Plus size={16}/>添加章节</button></section>)}</div>{chapters.error && <ErrorState error={chapters.error} retry={() => void chapters.refetch()}/>}<p className="settings-bottom-note">章节用于组织内容，不会改变 FSRS 的记忆计算。知识标签可以在编辑内容时自由添加。</p>{editing && <Modal title={editing.id ? '重命名章节' : '添加一个章节'} onClose={() => !busy && setEditing(null)} className="small-modal"><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await api(`/chapters${editing.id ? `/${editing.id}` : ''}`, { method: editing.id ? 'PATCH' : 'POST', body: JSON.stringify({ name: editing.name, subject: editing.subject }) }); refreshLearning(); setEditing(null); toast.success('章节已保存') } catch (e) { toast.error((e as Error).message) } finally { setBusy(false) } }}><div className="modal-body"><label className="field">章节名称<input autoFocus required maxLength={100} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })}/></label></div><div className="modal-footer"><button className="button primary" disabled={busy}>{busy ? <Spinner/> : <Check size={16}/>}保存章节</button></div></form></Modal>}</>
}

function APISettings() {
  const keys = useQuery({ queryKey: ['keys'], queryFn: () => api<APIKey[]>('/keys') })
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')
  const [scopes, setScopes] = useState(['read', 'write', 'review'])
  const [days, setDays] = useState('365')
  const [token, setToken] = useState('')
  const [busy, setBusy] = useState(false)
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); toast.success('已复制') } catch { toast.error('请选中文本后手动复制') } }
  const base = `${window.location.origin}/api/v1`
  return <div className="api-settings"><section className="panel api-intro"><span className="api-emblem"><KeyRound size={26}/></span><div><h2>让你的工具，也能帮你积累。</h2><p>脚本、笔记工具和外部助手，可以通过 API 管理同一份知识与复习记录。</p></div><a href="/api/docs" target="_blank" rel="noreferrer" className="button secondary">接口文档<ExternalLink size={15}/></a></section>
    <section className="panel settings-section"><div className="section-title"><h2>访问密钥</h2><button className="button primary small" onClick={() => { setCreating(true); setName('') }}><Plus size={15}/>创建密钥</button></div>{keys.error ? <ErrorState error={keys.error} retry={() => void keys.refetch()}/> : keys.data?.length ? <div className="key-list">{keys.data.map(k => <div className="key-entry" key={k.id}><KeyRound size={19}/><div><strong>{k.name}</strong><code>{k.prefix}••••••••</code><small>{k.scopes.map(s => ({ read: '读取', write: '编辑', review: '评分' })[s]).join(' · ')}　{ k.expires_at ? `${dateLabel(k.expires_at)} 到期` : '长期有效'}</small></div><button className="button secondary small danger" onClick={async () => { if (!window.confirm(`撤销“${k.name}”？使用它的外部工具将无法继续访问。`)) return; try { await api(`/keys/${k.id}`, { method: 'DELETE' }); await keys.refetch(); toast.success('密钥已撤销') } catch (e) { toast.error((e as Error).message) } }}>撤销</button></div>)}</div> : <Empty title="还没有外部连接" description="为每个工具创建独立密钥，方便按需授权和撤销。"/>}</section>
    <section className="panel settings-section api-guide"><h2>连接方式</h2><label className="field">API 地址<div className="copy-field"><code>{base}</code><button className="icon-button" aria-label="复制 API 地址" onClick={() => void copy(base)}><Copy size={16}/></button></div></label><p>请求头中添加 <code>Authorization: Bearer 你的密钥</code>。</p><div className="api-route-list">{[['GET', '/items', '搜索和获取知识列表'], ['POST', '/items', '新建知识或图片错题'], ['PATCH', '/items/{id}', '修改内容，保留复习进度'], ['DELETE', '/items/{id}', '移入回收站'], ['POST', '/media', '上传图片，获得附件 ID'], ['GET', '/reviews/due', '获取待复习内容'], ['POST', '/items/{id}/reviews', '提交真实表现并更新复习时间']].map(([method, path, note]) => <div key={method + path}><span className={`method ${method.toLowerCase()}`}>{method}</span><code>{path}</code><span>{note}</span></div>)}</div><p className="field-help">复习提交带上唯一 request_id 和当前 expected_version。同一次尝试重试时，沿用原请求，避免重复记分。</p></section>
    {creating && <Modal title="创建一把访问密钥" onClose={() => !busy && setCreating(false)} className="small-modal"><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { const result = await post<{ token: string }>('/keys', { name, scopes, expires_days: days ? Number(days) : null }); setToken(result.token); setCreating(false); await keys.refetch() } catch (e) { toast.error((e as Error).message) } finally { setBusy(false) } }}><div className="modal-body"><label className="field">给连接起个名字<input required autoFocus value={name} onChange={e => setName(e.target.value)} maxLength={80} placeholder="例如：我的笔记助手"/></label><div className="field"><label>授予哪些权限</label><div className="scope-checkboxes">{[['read', '读取知识与图片'], ['write', '新增、编辑与删除'], ['review', '提交和撤销复习评分']].map(([id, label]) => <label key={id}><input type="checkbox" checked={scopes.includes(id)} onChange={e => setScopes(s => e.target.checked ? [...s, id] : s.filter(x => x !== id))}/>{label}</label>)}</div></div><label className="field">有效期<select value={days} onChange={e => setDays(e.target.value)}><option value="30">30 天</option><option value="90">90 天</option><option value="365">1 年</option><option value="">长期有效</option></select></label></div><div className="modal-footer"><button className="button primary" disabled={busy || !scopes.length}>{busy ? <Spinner/> : <KeyRound size={16}/>}创建密钥</button></div></form></Modal>}
    {token && <Modal title="连接准备好了" onClose={() => setToken('')} className="small-modal"><div className="modal-body"><div className="settings-note"><ShieldCheck size={20}/><p>完整密钥只展示这一次。请复制并保存在对应工具中。</p></div><div className="new-token"><code>{token}</code></div><button className="button primary full-width" onClick={() => void copy(token)}><Copy size={16}/>复制密钥</button></div><div className="modal-footer"><button className="button secondary" onClick={() => setToken('')}>我已保存</button></div></Modal>}
  </div>
}

function DataSettings({ user }: { user: User }) {
  const [name, setName] = useState(user.display_name)
  const [password, setPassword] = useState({ current_password: '', new_password: '' })
  const [busy, setBusy] = useState('')
  const importRef = useRef<HTMLInputElement>(null)
  const exportData = async () => {
    setBusy('export')
    try { const response = await fetch('/api/v1/export', { credentials: 'same-origin' }); if (!response.ok) { const body = await response.json(); throw new Error(body.detail || '导出失败') } const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `拾忆备份-${new Date().toLocaleDateString('sv-SE')}.zip`; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast.success('完整备份已开始下载') } catch (e) { toast.error((e as Error).message) } finally { setBusy('') }
  }
  return <div className="data-settings"><section className="panel settings-section"><div className="settings-section-heading"><h2>把积累，妥善保管</h2><p>知识、题图、答案和复习历史，可以一起带走。</p></div><div className="backup-options"><div><span className="backup-icon"><Download size={25}/></span><h3>导出完整备份</h3><p>打包全部知识、图片、章节与复习历史。建议定期保存到另一处设备。</p><button className="button primary" disabled={!!busy} onClick={() => void exportData()}>{busy === 'export' ? <Spinner/> : <Download size={16}/>}下载备份 ZIP</button></div><div><span className="backup-icon"><Upload size={25}/></span><h3>导入已有积累</h3><p>导入拾忆备份，保留其中的记忆状态。内容作为独立条目添加，不覆盖现有资料。</p><button className="button secondary" disabled={!!busy} onClick={() => importRef.current?.click()}>{busy === 'import' ? <Spinner/> : <Upload size={16}/>}选择备份文件</button><input hidden ref={importRef} type="file" accept=".zip" onChange={async e => { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; if (!window.confirm('导入会添加独立条目与复习历史，不覆盖当前数据。重复导入同一个文件会自动跳过，确定继续吗？')) return; setBusy('import'); try { const body = new FormData(); body.append('file', file); const result = await api<{ imported: number; already_imported: boolean }>('/import', { method: 'POST', body }); refreshLearning(); toast.success(result.already_imported ? '这份备份已经导入过，没有重复添加' : `已导入 ${result.imported} 条内容及关联记录`) } catch (e) { toast.error((e as Error).message) } finally { setBusy('') } }}/></div></div><p className="field-help">备份中不包含账号密码、登录会话或 API 密钥。设置文件包含偏好供查阅，导入不会改动当前偏好。网页导入上限为 100 MB。</p></section>
    <section className="panel settings-section"><div className="settings-section-heading"><h2>你的名字</h2><p>让每一次回到这里，都有一点熟悉感。</p></div><form className="inline-name-form" onSubmit={async e => { e.preventDefault(); setBusy('name'); try { const updated = await api<User>('/preferences', { method: 'PUT', body: JSON.stringify({ ...user.preferences, display_name: name }) }); queryClient.setQueryData(['me'], updated); toast.success('称呼已更新') } catch (e) { toast.error((e as Error).message) } finally { setBusy('') } }}><label className="field">昵称<input value={name} maxLength={40} required onChange={e => setName(e.target.value)}/></label><button className="button secondary" disabled={!!busy}>保存称呼</button></form></section>
    <section className="panel settings-section"><div className="settings-section-heading"><h2>账号安全</h2><p>当前账号：{user.username}。修改密码后，其他设备需要重新登录。</p></div><form onSubmit={async e => { e.preventDefault(); setBusy('password'); try { await post('/auth/password', password); setPassword({ current_password: '', new_password: '' }); toast.success('密码已修改，其他登录会话已退出') } catch (e) { toast.error((e as Error).message) } finally { setBusy('') } }}><div className="form-row"><label className="field">当前密码<input type="password" autoComplete="current-password" required value={password.current_password} onChange={e => setPassword({ ...password, current_password: e.target.value })}/></label><label className="field">新密码<input type="password" autoComplete="new-password" minLength={10} maxLength={128} required value={password.new_password} onChange={e => setPassword({ ...password, new_password: e.target.value })} placeholder="至少 10 位"/></label></div><button className="button secondary" disabled={!!busy}>{busy === 'password' ? <Spinner/> : <LockKeyhole size={16}/>}更新密码</button></form></section>
  </div>
}
