import { useQuery } from '@tanstack/react-query'
import { ArrowRight, BookOpen, Clock3, Flame, Leaf, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { ratingNames, subjects } from '../lib'
import type { Stats } from '../types'
import { Empty, ErrorState, Heatmap, Loading, PageHeading, SectionTitle } from '../components/ui'

export default function Statistics() {
  const query = useQuery({ queryKey: ['stats'], queryFn: () => api<Stats>('/stats') })
  if (query.isPending) return <Loading/>
  if (query.error) return <ErrorState error={query.error} retry={() => void query.refetch()}/>
  const data = query.data
  const weekMax = Math.max(5, ...data.week.map(d => d.count))
  const forecastMax = Math.max(5, ...data.forecast.map(d => d.total))
  const totalRatings = Object.values(data.ratings).reduce((s, n) => s + n, 0)
  return <div className="statistics-page page-enter"><PageHeading eyebrow="SMALL STEPS, VISIBLE GROWTH" title="认真过的日子，有迹可循。" description="看看你已经走过的路，也为下一段旅程留一点余地。" actions={<span className="date-chip"><Leaf size={15}/>每一份积累都算数</span>}/>
    <div className="stats-metrics">{[{ icon: BookOpen, value: data.totals.reviews, unit: '次', label: '累计复习', color: 'sage' }, { icon: Clock3, value: data.totals.minutes, unit: '分钟', label: '累计专注', color: 'blue' }, { icon: Flame, value: data.totals.streak, unit: '天', label: '连续积累', color: 'clay' }, { icon: TrendingUp, value: data.totals.retention === null ? '—' : Math.round(data.totals.retention * 100), unit: data.totals.retention === null ? '' : '%', label: '近 30 天回忆成功率', color: 'sage' }].map(m => <div className="panel stat-metric" key={m.label}><span className={`metric-icon ${m.color}`}><m.icon size={20}/></span><span>{m.label}</span><strong>{m.value}<small>{m.unit}</small></strong></div>)}</div>
    <div className="stats-two-columns"><section className="panel chart-panel"><SectionTitle title="这一周，你的节奏" note="复习次数"/><div className="week-chart">{data.week.map((day, i) => <div className={`week-column ${i === 6 ? 'today' : ''}`} key={day.date}><span className="bar-value">{day.count}</span><div className="week-bar-track"><div style={{ height: `${Math.max(day.count ? 3 : 0, day.count / weekMax * 100)}%` }}/></div><span>{i === 6 ? '今天' : new Date(day.date + 'T12:00:00').toLocaleDateString('zh-CN', { weekday: 'short' })}</span></div>)}</div><div className="chart-caption"><span className="status-dot"/>本周累计 {data.week.reduce((s, d) => s + d.count, 0)} 次回忆，每一次都在加深连接。</div></section>
    <section className="panel chart-panel"><SectionTitle title="接下来，何时再相遇" note="未来 14 天"/><div className="forecast-chart">{data.forecast.map((day, i) => <div className="forecast-column" key={day.date} title={`${day.date} · ${day.total} 条`}><span>{day.total || ''}</span><div className="forecast-track">{subjects.map(s => <div key={s.id} className={s.color} style={{ height: `${day[s.id] / forecastMax * 100}%` }}/>)}</div><small>{i === 0 ? '今天' : day.date.slice(8)}</small></div>)}</div><div className="chart-legend">{subjects.map(s => <span key={s.id}><i className={s.color}/>{s.name}</span>)}</div><p className="field-help">仅统计当前已安排的复习，后续会随实际表现更新。</p></section></div>
    <div className="stats-two-columns"><section className="panel chart-panel"><SectionTitle title="各科的记忆温度" note="近 30 天实际表现"/><div className="subject-performance">{data.subjects.map(s => { const meta = subjects.find(x => x.id === s.subject)!; return <div key={s.subject}><span className={`performance-symbol ${meta.color}`}>{meta.symbol}</span><div><strong>{meta.name}</strong><div className="performance-track"><span className={meta.color} style={{ width: `${(s.retention ?? 0) * 100}%` }}/></div><small>{s.reviews_30d} 次复习 · {s.total} 条知识</small></div><b>{s.retention === null ? '—' : `${Math.round(s.retention * 100)}%`}</b></div> })}</div><p className="field-help">“困难 / 良好 / 轻松”均计为回忆成功。“忘记”计为失败；不等同于考试得分。</p></section><section className="panel chart-panel"><SectionTitle title="每一次真实的反馈" note="近 30 天"/>{totalRatings ? <><div className="rating-distribution">{[1, 2, 3, 4].map(r => <div key={r} className={`rating-${r}`} style={{ width: `${(data.ratings[r] ?? 0) / totalRatings * 100}%` }} title={`${ratingNames[r]}：${data.ratings[r] ?? 0} 次`}/>)}</div><div className="rating-breakdown">{[1, 2, 3, 4].map(r => <div key={r}><i className={`rating-${r}`}/><span>{ratingNames[r]}</span><b>{data.ratings[r] ?? 0}</b><small>{Math.round((data.ratings[r] ?? 0) / totalRatings * 100)}%</small></div>)}</div></> : <Empty title="真实反馈，让安排更合适" description="完成复习后，这里会展示你的表现分布。"/>}</section></div>
    <section className="panel year-panel"><SectionTitle title="积累，是一件安静的事" note={`近 13 周 · 过去一年活跃 ${data.totals.active_days} 天`}/><Heatmap days={data.heatmap}/><div className="heatmap-caption"><span>今天做一点，明天就多一点。</span><div>少<i className="level-0"/><i className="level-1"/><i className="level-2"/><i className="level-3"/><i className="level-4"/>多</div></div></section>
    <section className="panel weak-panel"><SectionTitle title="值得多一点耐心的知识" note="近 30 天出现过遗忘"/>{data.weak_items.length ? data.weak_items.map(i => <Link key={i.id} to={`/items/${i.id}`}><span className={`subject-badge ${subjects.find(s => s.id === i.subject)?.color}`}>{subjects.find(s => s.id === i.subject)?.name}</span><strong>{i.title}</strong><span>{i.lapses} 次遗忘</span><ArrowRight size={16}/></Link>) : <div className="quiet-empty"><Leaf size={21}/><p>这里会收集需要多一点关注的内容，陪你逐个理清。</p></div>}</section>
  </div>
}
